###### interform/handle/Makefile:	InterForm actor handles
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.interform.handle
TOPDIR=../../../..

FILES = \
	Actor.java \
	Element.java \
	Tagset.java

include $(TOPDIR)/makefiles/file.make
