### Makefile for Doc/Manuals
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Manuals
MYPATH=Doc/Manuals

SUBDIRS=Api Author Install InterForm User

include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make 
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
 
