###### pia/handle/Makefile:	DPS Tag handlers
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.pia.handle
TOPDIR=../../..

HANDLERS = \
	agentList.java \
	agentRunning.java \
	transControl.java \
	userMessage.java 

FILES=  $(HANDLERS)

include $(TOPDIR)/makefiles/file.make

### Dependencies:

