<h4> data.inc for Template </h4>
<t-data name=dName></t-data>
<t-doc name=dName label="Template Name">
       The name of the new template </t-doc>
<t-data name=dSystem type=checkbox>true</t-data>
<t-doc name=dSystem label="System template">
       (sets destination directory appropriately)</t-doc>
<t-data name=debug type=checkbox>true</t-data>
<t-doc name=debug label="Debug"></t-doc>

<b>Copyright &copy; 1997 Ricoh Silicon Valley</b><br>
<b>$Id$</b><br>
<hr>
