###### ii/Makefile:	InterForm Interpretor package.
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.ii
TOPDIR=../../..

FILES = \
	Actor.java \
	Interp.java \
	Parser.java \
	Tagset.java \
	Token.java \
	Tokens.java

include $(TOPDIR)/makefiles/file.make



