<!-- This file is meant to be included. -*-html-helper-*- -->
<!-- formatting ideas stolen from: 				   -->
<!-- 	http://barley.electriclichen.com/~dmarti/linuxmanship.html -->
<table border=0 width="100%" align=center cellspacing=0 cellpadding=5>
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <th align=center> Documentation Overview
  <tr> <th colspan=2 bgcolor="#c40026"> &nbsp;
       <td colspan=2 bgcolor=silver>&nbsp;

  <tr>  <td width=20>&nbsp;
    <th align=right valign=top bgcolor=silver><b>Release 2.0b:</b>
    <td>
	<a href="/PIA/README">README</a>,
        &nbsp;<a href="/PIA/INSTALL">INSTALL</a>,
        &nbsp;<a href="/PIA/Doc/Release">/Release&nbsp;notes/</a>, 
        &nbsp;<a href="/PIA/Doc/FAQ/">/FAQs/</a>
    </td><td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp; 
    <th align=right valign=top bgcolor=silver><b>Getting Started:</b>
    <td>
	<a href="/PIA/Doc/intro.html">Introduction</a>, 
	&nbsp;<a href="/PIA/Doc/Tutorial/index.html">Tutorial</a>,
	&nbsp;<a href="/PIA/Doc/Tutorial/syllabus.html">syllabus</a>,
	&nbsp;<a href="/PIA/Doc/Papers/BuildingNOA">Building&nbsp;NOA's</a>
    </td><td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver><b>Manuals:</b></th>
    <td>
	<a href="/PIA/Doc/Manuals/User/index.html">User's</a>, &nbsp;
	&nbsp;<a href="/PIA/Doc/Manuals/Author/index.html">Writing Agents</a>,
	&nbsp;<a href="/PIA/Doc/Manuals/InterForm/index.html">Active&nbsp;Docs</a>, 
	&nbsp;<a href="/PIA/Doc/Manuals/Api/index.html">Internals(API)</a>
    </td> <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver><b>Introductions:</b></th>
    <td>
	<a href="/PIA/Doc/pia_group.html">The PIA group</a>, 
	&nbsp;<a href="/PIA/Doc/vision.html">Our&nbsp;Vision</a>, 
	&nbsp;<a href="/PIA/Doc/Papers/LinuxWorld1999/">LinuxWorld1999</a>
    </td> <td bgcolor=silver>&nbsp; 
  <tr>	 <td>&nbsp;
    <th align=right valign=top bgcolor=silver>
	<a href="/PIA/Doc"><b>Other Docs:</b></a></th>
    <td><a href="/PIA/Doc/Papers/">/Papers/</a>,
	&nbsp;<a href="/PIA/Doc/Notes/">/Notes/</a> 
    </td> <td bgcolor=silver>&nbsp; 
  <if><test match='crc.ricoh.com'>&url;><then>
  <tr>	 <td>&nbsp;
    <!-- This row only appears inside Ricoh.  Should be an include -->
    <th align=right valign=top bgcolor=silver><b> Demonstrations:</b></th>
    <td>
	<a href="/PIA/Doc/demos.html">Appliances</a>, 
        &nbsp;<a href="http://ookami.crc.ricoh.com:8888/MB3/home.if">MediaBoard</a>,
	&nbsp;<a href="http://Forms:8000/">Form&nbsp;server</a>,
	&nbsp;<a href="http://gelion:8888/">Steve's&nbsp;pia</a>,
    </td> <td bgcolor=silver>&nbsp; 
  </tr>
  </if>
  <tr> <td>&nbsp; <td bgcolor=silver colspan=3>&nbsp;
</table>
<inc-footer cvsid="$Id$">
