<!-- This heading is meant to be included. -*-html-helper-*- -->
<table border=1 width="100%" align=center cellspacing=2 cellpadding=5>
  <tr> <th colspan=2>Documentation Overview</tr>
  <tr>	<th align=LEFT><b>Release 2.0b:</b></th>
    <td><a href="/PIA/README">README</a>, &nbsp;
        <a href="/PIA/INSTALL">INSTALL</a>, &nbsp;
        <a href="/PIA/Doc/Release">/Release notes/</a>, &nbsp;
        <a href="/PIA/Doc/FAQ/">/FAQs/</a>
    </td>
  </tr>

  <tr>	<th align=LEFT><b>Getting Started:</b></th>
    <td><a href="/PIA/Doc/intro.html">Introduction</a>, &nbsp;
	<a href="/PIA/Doc/Tutorial/index.html">Tutorial</a>, &nbsp;
	<a href="/PIA/Doc/Tutorial/syllabus.html">syllabus</a>, &nbsp;
	<a href="/PIA/Doc/Papers/BuildingNOA">Building NOA's</a>&nbsp;
    </td>
  </tr>

  <tr>	<th align=LEFT><b>Manuals:</b></th>
    <td><a href="/PIA/Doc/Manuals/User/index.html">User's</a>, &nbsp;
	<a href="/PIA/Doc/Manuals/Author/index.html">Writing Agents</a>, &nbsp;
	<a href="/PIA/Doc/Manuals/InterForm/index.html">Active Docs</a>, &nbsp;
	<a href="/PIA/Doc/Manuals/Api/index.html">Internals (API)</a>
    </td>
  </tr>

  <tr>	<th align=LEFT><b>Introductions:</b></th>
    <td><a href="/PIA/Doc/pia_group.html">The PIA group</a>, &nbsp;
	<a href="/PIA/Doc/vision.html">Our Vision</a>, &nbsp;
	<a href="/PIA/Doc/Papers/LinuxWorld1999/">LinuxWorld1999</a>
    </td>
  </tr>

  <tr>	<th align=LEFT><a href="/PIA/Doc"><b>Other Docs:</b></a></th>
    <td><a href="/PIA/Doc/Papers/">/Papers/</a>, &nbsp;
	<a href="/PIA/Doc/Notes/">/Notes/</a> 
    </td>
  </tr>
	
  <if><test match='crc.ricoh.com'>&url;><then>
  <tr><!-- This row only appears inside Ricoh.  Should be an include -->
    <th align=LEFT><b> Demonstrations:</b></th>
    <td><a href="/PIA/Doc/demos.html">Appliances</a>, &nbsp;
        <a href="http://ookami.crc.ricoh.com:8888/MB3/home.if">MediaBoard</a>,
        &nbsp;
	<a href="http://Forms:8000/">Form server</a>, &nbsp;
	<a href="http://gelion:8888/">Steve's pia</a>, &nbsp;
  </tr>
  </if>
</table>
<inc-footer cvsid="$Id$">
