#!/bin/sh
# $Id$
# This script fixes up your CVS information after the following:
#
#  moving pia/src/Agents to old/src/Agents
#  moving pia/InternalDoc to int/Doc and making it a module called InternalDoc
#

# First fix the repository paths.  It's not really necessary for 
#   the old dir's because they're going away, but we do it on principle.

echo "Fixing repository names -- this takes a while"
echo "src/Agents"
find src/Agents -name "Repository" -exec perl -p -i -e 's@/pia/src/Agents@/old/src/Agents@' {} \;
echo "src/java/w3c"
find src/java/w3c -name "Repository" -exec perl -p -i -e 's@/pia/src/java/w3c@/old/src/java/w3c@' {} \;
echo "InternalDoc"
find InternalDoc -name "Repository" -exec perl -p -i -e 's@/pia/InternalDoc@/int/Doc@' {} \;

# Now remove the modules that are going away from the Entries files.
echo "fixing CVS/Entries files"
perl -n -i -e 'm@/Agents/@ || print' src/CVS/Entries
perl -n -i -e 'm@/w3c/@ || print' src/java/CVS/Entries
perl -n -i -e 'm@/InternalDoc/@ || print' CVS/Entries

# Tell the user what to do next.

echo "It is recommended that you execute the following commands at this point:"
echo ' (You are unlikely to have any modified files in either of these...)'
echo "  (cd src/Agents; cvs release .)"
echo "  rm -rf src/Agents"
echo "  (cd src/java/w3c; cvs release .)"
echo "  rm -rf src/java/w3c"
echo " "
echo "You may also want to do one or more of the following:"
echo "  (cd ..; cvs -d /pia1/CvsRoot checkout int)"
echo "  (cd ..; diff -r int/Doc pia/InternalDoc)"
echo "  cvs release InternalDoc"
echo "  rm -rf InternalDoc;"
