PACKAGE=crc.util.regexp
TOPDIR=../../../..

FILES = \
	Chars.java \
	DList.java \
	DSList.java \
	DState.java \
	MatchInfo.java \
	NFABuildException.java \
	NList.java \
	RTree.java \
	RegExp.java \
	RegExpCore.java \
	RegExpDFA.java \
	RegExpDebug.java \
	RegExpNFA.java \
	RegExpParser.java \
	RegExpSyntaxException.java 




include $(TOPDIR)/makefiles/file.make



