###### dps/aux/Makefile:	DPS auxiliary classes
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.dps.aux
TOPDIR=../../..

FILES = \
	CurrentActive.java \
	CurrentNode.java \
	CursorStack.java 

include $(TOPDIR)/makefiles/file.make

### Dependencies
