### Makefile for Doc/Papers
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Papers
MYPATH=Doc/Papers
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
 
