<!-- template.inc for Document -->

<t-data name=tName type=hidden>Document</t-data>
<t-form label="Template for a new Document">
This form lets you create a new document, in the form of a directory that
contains either a single <a href="&dDOFS;/index.html">index.html</a> file, or
a separate file for each section.<p>
<strong>WARNING! It doesn't work yet...</strong><p>
The form was lifted from the Agent template, and hasn't been worked on.
</t-form>


<!-- Copyright &copy; 1997 Ricoh Silicon Valley -->
<!-- $Id$ -->
