PACKAGE=crc.pia

FILES = \
	Accepter.java \
	Transaction.java \
	Machine.java \
	Resolver.java \
	Content.java \
	Agent.java \
	ByteStreamContent.java \
	ContentFactory.java \
	GenericAgent.java \
	Logger.java \
	Pia.java \
	PiaInitException.java \
	PiaRuntimeException.java \
	FormContent.java 

include $(MAKEDIR)/file.make
