###### pia/Makefile:	Platform for Information Appliances
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.pia
TOPDIR=../../..

FILES = \
	Accepter.java \
	Transaction.java \
	Machine.java \
	Resolver.java \
	Content.java \
	Agent.java \
	ByteStreamContent.java \
	ContentFactory.java \
	GenericAgent.java \
	Logger.java \
	Pia.java \
	PiaInitException.java \
	PiaRuntimeException.java \
	FormContent.java 

include $(TOPDIR)/makefiles/file.make
