###### pia/Makefile:	Platform for Information Appliances
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.pia
TOPDIR=../../..

PACKAGES = \
	agent

FILES = \
	Accepter.java \
	Transaction.java \
	Machine.java \
	Resolver.java \
	Content.java \
	Agent.java \
	ByteStreamContent.java \
	ContentFactory.java \
	GenericAgent.java \
	Logger.java \
	Pia.java \
	PiaInitException.java \
	PiaRuntimeException.java \
	FormContent.java \
	HeaderFactory.java \
	Headers.java \
	ThreadPool.java \
	HTTPRequest.java \
	HTTPResponse.java

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make


