###### dps/input/Makefile:	InterForm Token input sources
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.dps.input
TOPDIR=../../..

FILES = \
	ExpandToken.java \
	Guard.java \
	SingleToken.java \
	Wrapper.java

include $(TOPDIR)/makefiles/file.make

### Dependencies:

ExpandToken.class: ../AbstractInputFrame.java  ../Input.java ../Token.java
SingleToken.class: ../AbstractInputFrame.java  ../Input.java
Wrapper.class: ../AbstractInputFrame.java  ../Input.java
