<!-- This heading is meant to be included using read. -->
<!-- Copyright 1997 Ricoh Silicon Valley -->
<table align=center cellspacing=0 cellpadding=0 border=0>
<tr nowrap nobr><th align=left width=170 valign=bottom nowrap><a
	href="http://rsv.ricoh.com/"><img src="/Agency/Icons/ricoh.gif"
	border=0 width=170 height=48 alt="R I C O H"></a>
    <th width=170 nowrap>
    <th align=left nowrap nobr valign=center>
        <a href="/"><img width=85 height=45 border=0
	    	         src="/Agency/Icons/pia45.gif" alt=PIA></a><br></tr>
<tr height=2><td colspan=3 bgcolor="#000000" nowrap nobr
    ><img src="/Agency/Icons/blackline.gif" height=2 width=425><br></tr>
<tr><th align=left><a href="http://rsv.ricoh.com/"><img
	src="/Agency/Icons/silicon-valley.gif" alt="Silicon Valley"
	border=0 width=170 height=21></a>
    <th>
    <th align=left><font face=helvetica><if><get entity name=title>
	<then><get entity name=title></then>
	<else>&agentName;/&fileName;</else></if></font>
</table>
<!-- $Id$ -->
