### Makefile for Doc/Notes
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley

PIADIR=../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Notes
MYPATH=Doc/Notes
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
include $(MF_DIR)/subdir.make

