<!-- Read by generic home.if --			 -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

<h2>About RAWHO agents</h2>

``&agentName;'' agents effectively  create hierarchical organizations of documents.  They provide means for adding links, automatically suggesting  categorizations, editing the hierarchy, and maintaining annotations.<p>

 These agents often run on a server shared by several people.  They can also function as local proxy agents  (e.g. putting a quick link adder in the control string).
<p>
RAWHO stands for Ricoh Assisted Working Hierarchical Organization.
<!-- $Id$ -->
