<!-- Read by generic home.if --			 -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

<h2>About RAWHO agents</h2>

``&agentName;'' agents  create (hierarchical) organizations of documents.
They provide means for adding links,  categories, [automatically suggesting  categorizations], editing the hierarchy, and maintaining annotations.<p>

 These agents often run on a server shared by several people.  
<p>
RAWHO stands for Ricoh Assisted Working Hierarchical Organization or something
like that.
<!-- $Id$ -->
