<table>
<TR><TH colspan=5>RAWHO agent 
<TR><TD> <a href="home.if">HOME</a>
<TD> <a href="show_category.if">Show</a>/<a href="edit_category.if">Edit</a> categories
<TD> <a href="show_link.if">Show</a>/<a href="edit_link.if">Edit</a>  link<a href="show_links.if">(s)</a>
<TD> <a href="edit_features.if"> edit features</a>
<TD> <a href="show_calendar.if">show calendar</a>
<TD> <a href="import.if"> Import list of links</a>
<TR><TD><a href="add_url.if"> add link</a> <TD> 
<TD><a href="add_category.if">add  category</a> <TD> 
<TD> <a href=notes.if>Notes</a>
</table>
<hr>
