<!-- Read by generic home.if --			 -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->

The &agentName; agent is used for generating directories full of files by
replacing (``expanding'') symbolic names in a set of prototype files with the
data you fill in on a form.  <p>

<strong>In most cases the template will not produce a complete application,
but will give you a framework to start with.  You will have to fill in the
details yourself with a text editor.</strong>

<!-- $Id$ -->
