### Makefile for /Doc
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Doc
MYPATH=Doc

SUBDIRS=Graphics Manuals Notes Papers 

include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make 
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
