PACKAGE=crc.tf

FILES = \
	 GetTitle.java \
	 GetAgent.java \
         IsAgReq.java \
 	 IsAgResp.java \
	 IsClNets.java \
	 IsFileRq.java \
	 IsHtml.java \
	 IsImage.java \
	 IsIntFrm.java \
	 IsLclSrc.java \
	 IsLocal.java \
	 IsPrxReq.java \
	 IsReques.java \
	 IsRespon.java \
	 IsText.java \
	 Registry.java \
	 UnknownNameException.java
	 

include $(MAKEDIR)/file.make



