PACKAGE=crc.tf

FILES = \
	 Title.java \
	 Agent.java \
         IsAgentRequest.java \
 	 IsAgentResponse.java \
	 IsClientNetscape.java \
	 IsFileRequest.java \
	 IsHtml.java \
	 IsImage.java \
	 IsInterform.java \
	 IsLclSrc.java \
	 IsLocal.java \
	 IsProxyRequest.java \
	 IsRequest.java \
	 IsResponse.java \
	 IsText.java \
	 Registry.java \
	 UnknownNameException.java
	 

include $(MAKEDIR)/file.make



