###### dps/active/Makefile:	DPS active document classes
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.dps.active
TOPDIR=../../..

INTERFACES = \
	ActiveNode.java \
	ActiveNodeList.java \
	ActiveAttrList.java \
	ActiveAttribute.java \
	ActiveComment.java \
	ActiveDocument.java \
	ActiveElement.java \
	ActiveEntity.java \
	ActivePI.java \
	ActiveText.java

CLASSES = \
	NotActiveNodeException.java \
	ParseNodeList.java \
	ParseTreeAttribute.java \
	ParseTreeAttrs.java \
	ParseTreeComment.java \
	ParseTreeElement.java \
	ParseTreeEntity.java \
	ParseTreePI.java \
	ParseTreeText.java

FILES = $(INTERFACES) $(CLASSES)

include $(TOPDIR)/makefiles/file.make

### Dependencies
