<!-- footer data for FMA -*-html-helper-*- -->

<!-- standard controls -->
<table align=center>
<TR><TD><a href="/&agentName;/home.if"><img src="/&agentName/Icons/fma.gif"
alt="FMA" width=64 height=32></a>
   <TD> <a href="/&agentName;/send_fax.if"> <img src="/&agentName/Icons/send.gif" alt="SEND" width=32
	height=32></a>
   <TD> <a href="/&agentName;/view_incoming.if"> <img src="/&agentName/Icons/incoming.gif" alt="IN" width=32
	height=32></a>
   <TD> <a href="/&agentName;/options.if"> <img src="/&agentName/Icons/admin.gif"
	alt="ADM" width=32 height=32></a>
   <TD> <a href="/My/&agentName;"> <img src="/&agentName/Icons/browse.gif"
	alt="BROWSE" width=32 height=32></a> 
</table>

