<route> <routestep>
            <routeid>1</routeid>
            <routeuser>user</routeuser>
            <routewhen>always</routewhen>
            <routecond> </routecond>
            </routestep><routestep>
            <routeid>2</routeid>
            <routeuser>printer</routeuser>
            <routewhen>always</routewhen>
            <routecond><conditional>
  <condvar>name</condvar>
  <condtest>equalto</condtest>
  <condval></condval>
  </conditional></routecond>
            </routestep><routestep>
            <routeid>3</routeid>
            <routeuser>Accounting</routeuser>
            <routewhen>always</routewhen>
            <routecond> </routecond>
            </routestep></route>
	  