#!/bin/sh
#	Display the names of files that contain a "hole"
#	$Id$

re="${1-[^=]===[^=]|unimplemented|eventually}"

find . '(' -name '*.java' -o -name '*htm?' -o -name '*.if' -o -name '*.tex' \
        -o -name '*.p[lm]' -o -name '*.inc' -o -name '*akefile' ')' -type f  \
	\! -path '*JavaDoc*' \! -path '*/other/*' \
    -exec egrep -i -l "$re" {} \; 
