PACKAGE="crc"

PACKAGES = \
	pia \
	ds \
	if \
	tf \
	util

# mail, mime

include $(MAKEDIR)/package.make

javadoc::
	rm -f ../../CRC/WWW/User/api/*.html
	javadoc -d ../../CRC/WWW/User/api \
		crc.pia 













