###### crc/Makefile:	Ricoh California Research Center's Java classes.
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE="crc"
TOPDIR=../..

PACKAGES = \
	ds \
	interform \
	pia \
	tf \
	util

# mail, mime

include $(TOPDIR)/makefiles/package.make














