###### crc/Makefile:	Ricoh California Research Center's Java classes.
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE="crc"
TOPDIR=../..

PACKAGES = \
	ds \
	interform \
	pia \
	sgml \
	tf \
	util

PACKAGENAMES= \
	crc.ds \
	crc.interform crc.interform.handle \
	crc.pia crc.pia.agent \
	crc.sgml \
	crc.tf \
	crc.util

# mail, mime

include $(TOPDIR)/makefiles/package.make














