###### org/w3c/Makefile:	World Wide Web Consortium
# 	$Id$
#	Copyright 1998, Ricoh Silicon Valley

PACKAGE=org.w3c
TOPDIR=../..

PACKAGES = \
	dom

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make
