### Makefile for Doc/Notes/steve
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=steve
MYPATH=Doc/Notes/steve
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
 
