<!-- Read by generic home.if --			 -*-html-helper-*- -->

<h2>About Spy agents</h2>

``&agentName;'' agents effectively ``spy on'' HTTP transactions, and report
their findings to you (the ``spymaster'').   Usually this is done by attaching
a ``toolbar'', in the form of a line or two of text, to the top of a
document. <p> 

By tongue-slightly-in-cheek convention, Spy agents are named after well-known
espionage agents or agencies.

<inc-footer cvsid="$Id$">
