### Makefile for Doc/Papers/LinuxWorld1999/Images
#	$Id$	
# 	COPYRIGHT 1998, Ricoh Silicon Valley

PIADIR=../../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=Images
MYPATH=Doc/Papers/LinuxWorld1999/Images
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make

