PACKAGE=crc.content.text
TOPDIR=../../..


FILES = \
	Default.java \
	html.java \
	ParsedContent.java \
	InterFormContent.java \
	ProcessedContent.java \
	StringContent.java

include $(TOPDIR)/makefiles/file.make

### Dependencies:

Default.class:	../StreamingContent.java

html.class:  Default.java 


