###### dps/input/Makefile:	InterForm Token input sources
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.dps.input
TOPDIR=../../..

FILES = \
	ToDocument.java \
	ToWriter.java

include $(TOPDIR)/makefiles/file.make

