###### dps/parse/Makefile:	InterForm parsers
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.dps.parse
TOPDIR=../../..

FILES = \
	BasicParser.java

include $(TOPDIR)/makefiles/file.make

### Dependencies:


