###### org/Makefile:	Imported organizations' Java classes
#	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE="org"
TOPDIR=..

### These are the packages to be built.  
###	Only the top-level directories are needed; 
###	make descends into each one recursively.

PACKAGES = \
	w3c

include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make














