### Makefile for Doc/Papers/LinuxWorld1999
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley

PIADIR=../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=LinuxWorld1999
MYPATH=Doc/Papers/LinuxWorld1999
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
include $(MF_DIR)/subdir.make

SUBDIRS= Images

all:: lw99.slides.html architecture.slides.html who-what.slides.html \
	open-source.slides.html appendices.slides.html

