### Makefile for Doc/Papers/LinuxWorld1999
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=../../..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=LinuxWorld1999
MYPATH=Doc/Papers/LinuxWorld1999
include $(MF_DIR)/file.make
include $(MF_DIR)/graphics.make
include $(MF_DIR)/text.make
 
