###### util/Makefile:	PIA Utilities package
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.util
TOPDIR=../../..

FILES = \
	Utilities.java \
	Timer.java

include $(TOPDIR)/makefiles/file.make




