###### ds/Makefile:	Data Structure package.
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.ds
TOPDIR=../../..

FILES = \
	Features.java \
	List.java \
	Queue.java \
	Table.java \
	Thing.java \
	UnaryFunctor.java \
	TernFunc.java \
	Stuff.java 

include $(TOPDIR)/makefiles/file.make

List.class: Stuff.java

Table.class: Stuff.java

Thing.class: Stuff.java
