###### ds/Makefile:	Data Structure package.
# 	$Id$
#	Copyright 1997, Ricoh California Research Center

PACKAGE=crc.ds
TOPDIR=../../..

FILES = \
	Features.java \
	Queue.java \
	Thing.java \
	UnaryFunctor.java \
	TernFunc.java

include $(TOPDIR)/makefiles/file.make



