### Makefile for src
#	$Id$	
# 	COPYRIGHT 1997, Ricoh Silicon Valley
 
PIADIR=..
MF_DIR=$(PIADIR)/Config/makefiles
MYNAME=src
MYPATH=src

SUBDIRS=java

include $(MF_DIR)/file.make
include $(MF_DIR)/subdir.make 
