###### pia/Makefile:	Platform for Information Appliances
#	$Id$
#	Copyright 1998, Ricoh California Research Center

PACKAGE=crc.dom
TOPDIR=../..

PACKAGES =

FILES = \
	Attribute.java \
	AttributeList.java \
	Comment.java \
	DOM.java \
	DOMFactory.java \
	Document.java \
	DocumentContext.java \
	EditableNodeList.java \
	Element.java \
	NamedNodeList.java \
	NoSuchNodeException.java \
	Node.java \
	NodeType.java \
	NodeEnumerator.java \
	NodeList.java \
	NotMyChildException.java \
	PI.java \
	Text.java \
	AbstractDOMFactory.java \
	AbstractDocument.java  \
	AbstractNamedList.java \
        AbstractNode.java  \
	AppDocument.java \
	AppNamedNodeList.java \
	AppPI.java \
	AppText.java \
	CRCDOM.java \
	CRCDOMFactory.java \
	BasicElement.java \
	BasicAttr.java \
	CRCAttribute.java \
	AppComment.java \
	ChildNodeList.java \
	ChildNodeListEnumerator.java \
	LinkedNodeList.java \
	EditNodeListEnumerator.java \
	ArrayNodeList.java \
	AttrList.java \
	Report.java \
	Logger.java \
	AttributeDefinition.java \
	CDATASection.java \
	ConnectionType.java \
	ContentType.java \
	DeclaredValueType.java \
	DefaultValueType.java \
	DocumentType.java \
	ElementDefinition.java \
	ElementToken.java \
	ModelGroup.java \
	Notation.java \
	OccurrenceType.java \
	PCDATAToken.java \
	CRCElement.java

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make

### Dependencies:
