###### pia/Makefile:	Platform for Information Appliances
#	$Id$
#	Copyright 1998, Ricoh California Research Center

PACKAGE=crc.dom
TOPDIR=../..

PACKAGES =

FILES = \
	AbstractDOMFactory.java \
	AbstractDocument.java  \
	AbstractNamedList.java \
        AbstractNode.java  \
	AppDocument.java \
	AppNamedNodeList.java \
	AppPI.java \
	AppText.java \
	CRCDOM.java \
	CRCDOMFactory.java \
	BasicElement.java \
	BasicAttr.java \
	AttrNodeDef.java \
	Attr.java \
	AppComment.java \
	ChildNodeList.java \
	ChildNodeListEnumerator.java \
	LinkedNodeList.java \
	EditNodeListEnumerator.java \
	ArrayNodeList.java \
	AttrList.java

include $(TOPDIR)/makefiles/file.make
include $(TOPDIR)/makefiles/package.make

### Dependencies:
