###### pia/Makefile:	Platform for Information Appliances
#	$Id$
#	Copyright 1998, Ricoh California Research Center

PACKAGE=crc.dom
TOPDIR=../..

PACKAGES =

FILES = \
	NodeWrapper.java \
	LinkedList.java \
	LinkedNodeListEnumerator.java \
	Attribute.java \
	AttributeList.java \
	Comment.java \
	DOM.java \
	DOMFactory.java \
	Document.java \
	CRCDocument.java \
	DocumentContext.java \
	ArrayNodeListEnumerator.java \
	Element.java \
	NamedNodeList.java \
	NoSuchNodeException.java \
	Node.java \
	NodeType.java \
	NodeEnumerator.java \
	NodeList.java \
	NotMyChildException.java \
	PI.java \
	Text.java \
	AbstractDOMFactory.java \
	AbstractDocument.java  \
	AbstractNamedList.java \
        AbstractNode.java  \
	BasicDocument.java \
	BasicNamedNode.java \
	BasicNamedNodeList.java \
	BasicPI.java \
	BasicText.java \
	BasicDOMFactory.java \
	CRCDOM.java \
	CRCDOMFactory.java \
	BasicElement.java \
	BasicAttribute.java \
	CRCAttribute.java \
	BasicComment.java \
	ChildNodeList.java \
	ChildNodeListEnumerator.java \
	LinkedNodeList.java \
	ArrayNodeList.java \
	AttrList.java \
	Report.java \
	Logger.java \
	AttributeDefinition.java \
	CDATASection.java \
	ConnectionType.java \
	ContentType.java \
	DeclaredValueType.java \
	DefaultValueType.java \
	DocumentType.java \
	ElementDefinition.java \
	ElementToken.java \
	ModelGroup.java \
	Notation.java \
	OccurrenceType.java \
	PCDATAToken.java \
	CRCElement.java \
	Entity.java \
	InternalEntity.java \
	ExternalEntity.java \
	ExternalTextEntity.java \
	ExternalNDATAEntity.java \
	AbstractEntity.java \
	NdataEntity.java \
	TextEntity.java \
	AgentEntity.java \
	LocalEntity.java \
	SystemEntity.java

include $(TOPDIR)/makefiles/file.make
#include $(TOPDIR)/makefiles/package.make

### Dependencies:
