###### org/w3c/dom/Makefile:	Document Object Model
# 	$Id$


PACKAGE=org.w3c.dom
TOPDIR=../../..

FILES = $(wildcard *.java)

# Note that at the moment we are not building the HTML classes,
# since we don't use them. 

# include $(TOPDIR)/makefiles/package.make
include $(TOPDIR)/makefiles/file.make

