<route> <routestep>
            <routeid>1</routeid>
            <routeuser>user</routeuser>
            <routewhen>always</routewhen>
            <routecond> </routecond>
            </routestep><routestep>
            <routeid>2</routeid>
            <routeuser>Accounting</routeuser>
            <routewhen>always</routewhen>
            <routecond> </routecond>
            </routestep></route>
	  