<!-- This heading is meant to be included using read. -*-html-helper-*- -->
<!-- Copyright 1997 Ricoh Silicon Valley -->
<table align=center cellspacing=0 cellpadding=0 border=0>
<tr nowrap nobr><th align=left width=170 valign=bottom nowrap><a
	href="http://rsv.ricoh.com/"><img src="/Agency/Icons/ricoh.gif"
	border=0 width=170 height=48 alt="R I C O H"></a></th>
    <th width=170 nowrap></th>
    <th align=left nowrap nobr valign=center>
        <a href="http://www.ricoh.com/newaf.html"><img width=85 height=45 border=0
	    	         src="/&agentName/Icons/aficio.gif" alt=AFICIO></a></th></tr>
<tr height=2><td colspan=3  nowrap nobr
    ><img src="/Agency/Icons/blackline425.gif" height=2 width=425></td></tr>
<tr nowrap nobr><th align=left valign=top><a href="/"><img
	src="/&agentName/Icons/fma.gif" alt="FMA"
	border=0 width=170 height=21></a>
    <th></th>
    <th align=left><font face=helvetica><if><get entity name=title>
	<then><get entity name=title></then>
	<else>&agentName;/&fileName;</else></if></font><br></th></tr>
</table>

<!-- $Id$ -->
