<html>
<head>
<title>WhoWhere? E-mail Addresses</title>

<!-- search form -->

<FORM METHOD="GET" ACTION="http://query1.whowhere.com/jwz/name.wsrch">
<font size=3 face=times>

<!--start EMAIL_SEARCH_CONTENT substs (used to be called INDEX_HTML_CONTENT)-->
<table width=420 border=0 CELLPADDING=4>
<tr valign=center><td colspan=2>
<img src="http://www.whowhere.com/images/hdr_email_addresses.gif" border=0 alt="E-mail Addresses" width=420 height=21><br>
</td></tr>
<tr valign=center><td align=right nowrap>
<b><font size=2 face=times>Person's Name</font></b><br>
<font size=2 face=times>(required; in any order)</font><br>
</td><td>
<INPUT size="30" name="name">
</td></tr>
<tr valign=center><td align=right nowrap>
<b><font size=2 face=times>Domain Name</font></b><br>
<font size=2 face=times>(e.g.: aol.com)</font>
</td><td>
<INPUT size="30" name="org">
</td></tr>
<tr valign=center><td align=right nowrap>
<font size=2 face=times>
<b>Show me</b></font>
</td><td>
<input type=radio checked value=exact name=match> <font size=2 face=times>Only exact matches</font><br>
<input type=radio value=inexact name=match><font size=2 face=times> All matches</font>
</td></tr>
<tr valign=center>
<td colspan=2>
<img src="http://www.whowhere.com/images/dot.gif" width=340 height=1 alt="dot">
<font size=2 face=times><input type="submit" value="Find"></font>
</td></tr>
<tr valign=top><td colspan=2>
<img src="http://www.whowhere.com/images/bracket_bottom.gif" width=420 height=8>
</td></tr>
</table>
<br>
</form>
<!--end EMAIL_SEARCH_CONTENT substs (used to be called INDEX_HTML_CONTENT)-->
</font>

<!-- end search form -->
</body></html>
<!--end BN substs-->

