<!-- search form -->
<form action="http://www.whowhere.com/srvredirect" method=get>
<table border=0>
<tr><td>

<b><font size=3 face=times>First Name</font></b>
</td><td>

<input type="text" size=15 name="f-name">

</td></tr>

<tr><td>

<b><font size=3 face=times>Last Name</font></b>

</td><td>

<input type="text" size=15 name="name">

</td></tr>
</table><br>
						
<table border=0>
<tr valign=top>
<td align=right>

<b><font size=3 face=times>E-Mail</font></b><br>

<font size=3 face=times><a href="http://www.whowhere.com/AdvancedE">Advanced</a></font><br>



&nbsp;<br>

</td><td>

<input type="radio" name="find" value="email" checked>

</td><td rowspan=2>

<br>
<br>

<!-- input type="image" src="http://www.whowhere.com/images/button_find.gif" name="submit" border=0 hspace=3 alt="Find"><br-->
<input type="submit" value="Find">
</td></tr>

<tr valign=top><td align=right>

<b><font size=3 face=times>Phone &amp; Address</font></b><br>

<font size=3 face=times><a href="http://www.whowhere.com/Phone">Advanced</a></font><br>
</td><td>

<font size=3 face=times><input type="radio" name="find" value="phone"></font>

</td></tr>
</table><br>
</form>
<!-- end search form -->
<br>
